// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDPVjHem7ipaf4KWz8JbpomAs6f9bitoo',
    appId: '1:823030843988:web:7bef8b8c500513ac033bc1',
    messagingSenderId: '823030843988',
    projectId: 'health-buddy-ea23f',
    authDomain: 'health-buddy-ea23f.firebaseapp.com',
    storageBucket: 'health-buddy-ea23f.firebasestorage.app',
    measurementId: 'G-P3B0D1GFLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFmjtfDi5a2iUvFo94_S7-l0rpZBblr4E',
    appId: '1:823030843988:android:635d6426e806ceae033bc1',
    messagingSenderId: '823030843988',
    projectId: 'health-buddy-ea23f',
    storageBucket: 'health-buddy-ea23f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZD_aWA1uZhfPMeOr-wsUN2tK66x_uhco',
    appId: '1:823030843988:ios:0f90f82d03a4bdd0033bc1',
    messagingSenderId: '823030843988',
    projectId: 'health-buddy-ea23f',
    storageBucket: 'health-buddy-ea23f.firebasestorage.app',
    iosBundleId: 'com.example.healthBuddyNewapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZD_aWA1uZhfPMeOr-wsUN2tK66x_uhco',
    appId: '1:823030843988:ios:0f90f82d03a4bdd0033bc1',
    messagingSenderId: '823030843988',
    projectId: 'health-buddy-ea23f',
    storageBucket: 'health-buddy-ea23f.firebasestorage.app',
    iosBundleId: 'com.example.healthBuddyNewapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDPVjHem7ipaf4KWz8JbpomAs6f9bitoo',
    appId: '1:823030843988:web:56e15cd028f4f43d033bc1',
    messagingSenderId: '823030843988',
    projectId: 'health-buddy-ea23f',
    authDomain: 'health-buddy-ea23f.firebaseapp.com',
    storageBucket: 'health-buddy-ea23f.firebasestorage.app',
    measurementId: 'G-ZF00GLRZFP',
  );
}
